name: Greetings

on:
  pull_request_target:
    types: [closed]
  issues:
    types: [closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      if: |
        (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) ||
        (github.event_name == 'issues')
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          ## Congratulations! The Issue you created has been closed.

          The issue you created has been closed. Thank you for your valuable feedback to the Known team!
        pr-message: |
          ## Congratulations! The Pull Request you created has been merged.
          
          After rigorous review and testing by the Known team, we have determined that your Pull Request aligns with Known's consistent development and design philosophy since its establishment. It holds the potential to bring technical, universal, localised, or improved benefits to the future development of this open-source project and demonstrates excellent stability. Therefore, we have merged this PR. On behalf of all users, the Known team would like to express our sincere gratitude and regards to you for your selfless contributions to the Known project and the education industry!
